Refactor network IO tracking.
phpredis/phpredis pull request #2261
Opened 2022-11-24 20:00 UTC by michael-grunder

* Create inline wrappers of the low-level php_stream_* functions that also keep track of the number of bytes written/read.

* Change the logic to aggregate network traffic until the user explicitly "resets" it.  I think this will be a more common use-case (running many commands and then seeing overall network IO).

See #2106

2022-11-24 20:03 UTC, michael-grunder commented
@yatsukhnenko I reworked the logic here a little bit.

I added tracking of bytes in as well as out, and instead of bookkeeping in various different areas, just wrapped every low-level `php_stream_*` function we call, and did the bookkeeping there.

One other thing to note is that in `redis_sock_read_bulk` I noticed that we were using a `size_t` for the return value of `redis_sock_read`, but this should be a `ssize_t` as it can return -1 on error.

cc @tillkruss Let me know if you have any comments.

2022-11-25 10:39 UTC, yatsukhnenko requested changes
Also CodeQL isn't happy with variables names in nested loops

2022-11-25 10:39 UTC, yatsukhnenko commented on library.c
> +        php_stream_write(redis_sock->stream, cmd, sz) == sz)
Use `redis_sock_write_raw` here

2022-11-25 20:36 UTC, yatsukhnenko approved these changes

2022-11-25 21:41 UTC, merged