Add compression support for PHP Sessions
phpredis/phpredis pull request #2473
Opened 2024-04-03 15:24 UTC by bitactive

Previously, compression was available for standard data but not for session handling. This update enables the compression of PHP sessions, allowing for more efficient Redis memory usage.

2024-04-03 15:42 UTC, bitactive commented
The failed checks result from an igbinary issue on macOS, not related to this commit

2024-04-06 20:19 UTC, michael-grunder requested changes
This looks great.  

I suppose you could also abstract the `redis_compress` and `redis_uncompress` logic that is each done exactly the same way twice into a helper that would return nonzero if the resulting value needs to be freed, but that's a minor nitpick

2024-04-06 20:19 UTC, michael-grunder commented on redis_session.c
> +    if(strcmp(INI_STR("redis.session.compression"), "lzf") == 0) {
```suggestion
    if(strncasecmp(INI_STR("redis.session.compression"), ZEND_STRL("lzf")) == 0) {
```

2024-04-06 20:19 UTC, michael-grunder commented on redis_session.c
> +    if(strcmp(INI_STR("redis.session.compression"), "lz4") == 0) {
```suggestion
    if(strncasecmp(INI_STR("redis.session.compression"), ZEND_STRL("lz4")) == 0) {
```

2024-04-06 20:19 UTC, michael-grunder commented on redis_session.c
> +    if(strcmp(INI_STR("redis.session.compression"), "zstd") == 0) {
```suggestion
    if(strncasecmp(INI_STR("redis.session.compression"), ZEND_STRL("zstd")) == 0) {
```

2024-04-06 20:19 UTC, michael-grunder commented on redis_session.c
> +
Maybe it's worth issuing an E_NOTICE `php_error_docref` here if the INI setting is not empty and not "none"?

2024-04-08 15:22 UTC, bitactive commented
Thank you for your review and suggestions. Could you please check if everything is now fine or if further improvements are needed?

2024-04-08 17:09 UTC, michael-grunder reviewed
Sorry about the `ZEND_STRL` Windows issue, I knew it confused Windows but had forgotten it in my old age.  :smile:

If you update the compress/uncompress helpers to always set the out args I'll get this merged.

I'm also happy to write a test for it.  The session tests are a bit involved.

2024-04-08 17:09 UTC, michael-grunder commented on redis_session.c
> +    if(strncasecmp(INI_STR("redis.session.compression"), ZEND_STRL("lzf")) == 0) {
```suggestion
    if(strncasecmp(INI_STR("redis.session.compression"), "lzf", sizeof("lzf") - 1) == 0) {
```

2024-04-08 17:09 UTC, michael-grunder commented on redis_session.c
> +    if(strncasecmp(INI_STR("redis.session.compression"), ZEND_STRL("lzf")) == 0) {
I forgot windows gets confused when you combine `strncasecmp` with `ZEND_STRL`

2024-04-08 17:09 UTC, michael-grunder commented on redis_session.c
> +    if(strncasecmp(INI_STR("redis.session.compression"), ZEND_STRL("zstd")) == 0) {
Same as lzf

2024-04-08 17:09 UTC, michael-grunder commented on redis_session.c
> +    if(strncasecmp(INI_STR("redis.session.compression"), ZEND_STRL("none")) == 0) {
see above

2024-04-08 17:09 UTC, michael-grunder commented on redis_session.c
> +}
```suggestion
static int session_uncompress_data(RedisSock *redis_sock, char *data, size_t len,
                                   char **decompressed_data, size_t *decompressed_len) {
    if (redis_sock->compression) {
        if(redis_uncompress(redis_sock, decompressed_data, decompressed_len, data, len)) {
            return 1;
        }
    }

    *decompressed_data = data;
    *decompressed_len = len;

    return 0;
}
```

2024-04-08 17:09 UTC, michael-grunder commented on redis_session.c
> +}
```suggestion
static int
session_compress_data(RedisSock *redis_sock, char *data, size_t len,
                      char **compressed_data, size_t *compressed_len)
{
    if (redis_sock->compression) {
        if(redis_compress(redis_sock, compressed_data, compressed_len, data, len)) {
            return 1;
        }
    }

    *compressed_data = data;
    *compressed_len = len;

    return 0;
}
```

2024-04-08 17:09 UTC, michael-grunder commented on redis_session.c
> +        }
If you change `session_compress_data` to always set the out arguments and return whether you need to free the char * you can eliminate this if/else and just always use `compressed_buf` and then conditionally free it based on the return value from `session_compress_data`.

2024-04-08 17:09 UTC, michael-grunder commented on redis_session.c
> +        if (session_uncompress_data(c->flags, reply->str, reply->len, &compressed_buf, &compressed_len)) { // Try uncompress
Same idea as `session_compress_data` with this uncompress block.

2024-04-08 17:51 UTC, bitactive commented
Thank you for the advice. It should be better now.

2024-04-08 21:40 UTC, merged

2024-04-08 21:40 UTC, michael-grunder commented
Merged, thanks!