Initialize array with known size
phpredis/phpredis pull request #2574
Opened 2024-11-21 11:27 UTC by JakubOnderka

We known in advance the array size, so it makes sense to avoid reallocation when adding new elements

2024-11-21 19:30 UTC, michael-grunder commented on library.c
> +    array_init_size(&z_multi_result, numElems); /* pre-allocate array for multi's results. */
I think we need to account for `numElems == -1`

2024-11-21 19:31 UTC, michael-grunder commented on library.c
> +    array_init_size(&z_multi_result, numElems);
Same as the previous comment. `numElems` might be `-1`.

2024-11-21 19:32 UTC, michael-grunder requested changes
Good optimization, just need to account for `*-1\r\n`

2024-11-21 21:19 UTC, JakubOnderka commented
> Good optimization, just need to account for `*-1\r\n`

Fixed. Now even when number of elements is -1 or 0, immutable empty array is used – this will avoid even more allocations.

2024-11-25 17:22 UTC, michael-grunder commented on redis.c
> +    array_init_size(z_tab, count);
It would be interesting to profile whether this is actually faster in practice, given that the `HashTable` grows exponentially.

2024-11-25 17:35 UTC, michael-grunder commented on redis.c
> +    array_init_size(z_tab, count);
I think we should remove this commit from the PR until there are numbers showing it improves performance on average.

2024-11-25 17:37 UTC, michael-grunder requested changes
This is great. As in my comment I think we need numbers to justify double-iterating the multi/pipeline linked list, but if you want to remove that commit I'll rebase the other changes in this PR into develop.

2024-11-25 18:47 UTC, JakubOnderka commented
Cherry picked to separate PR #2583 and removed from this branch, so it should be possible to merge it.

2024-11-25 21:20 UTC, michael-grunder approved these changes

2024-11-26 17:51 UTC, yatsukhnenko approved these changes

2024-11-26 18:39 UTC, merged

2024-11-26 18:39 UTC, michael-grunder commented
Merged, thanks!